image: atlassian/default-image:3

pipelines:
  branches:
    main:
      - step: 
          name: Build and test
          script:
            - IMAGE_NAME=$BITBUCKET_REPO_SLUG
            - docker build -t ${IMAGE_NAME} .
            - docker save ${IMAGE_NAME} --output "${IMAGE_NAME}.tar"
          services:
            - docker
          caches:
            - docker
          artifacts:
            - "*.tar"
      - step:
          name: Deploy
          deployment: Production
          script:
            - echo ${REGISTRY_PASSWORD} | docker login -u "$REGISTRY_USERNAME" --password-stdin "$REGISTRY_NAME"
            - IMAGE_NAME=$BITBUCKET_REPO_SLUG
            - docker load --input "${IMAGE_NAME}.tar"
            - VERSION="prod-0.1.${BITBUCKET_BUILD_NUMBER}"
            - IMAGE=${REGISTRY_NAME}/${REGISTRY_NAMESPACE}/$IMAGE_NAME
            - docker tag "${IMAGE_NAME}" "${IMAGE}:${VERSION}"
            - docker tag "${IMAGE_NAME}" "${IMAGE}:latest"
            - docker push "${IMAGE}:${VERSION}"
            - docker push "${IMAGE}:latest"
          services:
            - docker

